### Registrar usuário
POST http://127.0.0.1:3333/register HTTP/1.1
Content-Type: application/json

{
    "name": "Alice Martins",
    "email": "martinsalice280206@gmail.com",
    "password": "123456"
}

### Autenticar usuário
POST http://127.0.0.1:3333/loginHTTP/1.1
Content-Type: application/json

{
    "email": "martinsalice280206@gmail.com",
    "password": "123456"
}